include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - unnecessary_const
    - avoid_print
    - always_declare_return_types
    - directives_ordering
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
  errors:
    missing_return: warning
    dead_code: warning