name: Flutter CI

on:
  push:
    branches: [ main, feature/dicoding-rating5 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build web --release
      - run: flutter build apk --release